default:
  default_args:
    start_date: 2025-07-21
    retries: 1
    retry_delay_sec: 300
  tags: ['aws', 'datasync', 'landing']
  max_active_runs: 1

test_datasync_operator:    
  description: Test DataSync Operator
  render_template_as_native_obj: True
  schedule: 8 1 * * *
  owner: ['hiroyukii.seo@gmail.com']
  task_groups:
    landing:
      tooltip: This group process pipeline
      dependencies: []
    
  tasks:
    landing.task1:
      operator: airflow.providers.amazon.aws.operators.datasync.DataSyncOperator
      task_arn: "{{  var.value.built_landing_datasync_arn  }}"
      aws_conn_id: aws_default
      wait_for_completion: True
      task_group_name: landing
      dependencies: []