apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: trip-analytics-{{ ts_nodash|lower}}-{{ task_instance.try_number }}
  namespace: processing
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "seoerick/trip_analytics:0.0.1"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/main.py
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark
    env:
      - name: ACCESS_KEY
        value: "minioadmin"
      - name: SECRET_KEY
        value: "minioadmin"
      - name: S3_ENDPOINT
        value: "http://minio-service.minio.svc.cluster.local:9000"
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.5.0
    env:
      - name: ACCESS_KEY
        value: "minioadmin"
      - name: SECRET_KEY
        value: "minioadmin"
      - name: S3_ENDPOINT
        value: "http://minio-service.minio.svc.cluster.local:9000"

