default:
  default_args:
    start_date: 2025-07-24
    retries: 1
    retry_delay_sec: 300
  tags: ['teste']
  max_active_runs: 1

empty_pipeline_teste:    
  description: This is a dummy pipeline for testing purposes.
  render_template_as_native_obj: True
  schedule: 8 1 * * *
  owner: ['hiroyukii.seo@gmail.com']
  task_groups:
    group1:
      tooltip: This is the first task group.
      dependencies: []
  tasks:
    group1.task1:
      operator: airflow.operators.empty.EmptyOperator
      task_group_name: group1
      dependencies: []
      outlets: [group1.task1]
    group1.task2:
      operator: airflow.operators.empty.EmptyOperator
      task_group_name: group1
      dependencies: []
      outlets: [group1.task2]
    group1.task3:
      operator: airflow.operators.empty.EmptyOperator
      task_group_name: group1
      dependencies: ['group1.task1', 'group1.task2']
      outlets: [group1.task3]

empty_pipeline_teste2:    
  description: This is a dummy pipeline for testing purposes.
  render_template_as_native_obj: True
  schedule: 
    or:
      - __type__: airflow.sdk.Asset
        uri: group1.task1
      - __type__: airflow.sdk.Asset
        uri: group1.task2
  owner: ['hiroyukii.seo@gmail.com']
  task_groups:
    group2:
      tooltip: This is the first task group.
      dependencies: []
  tasks:
    group2.task1:
      operator: airflow.operators.empty.EmptyOperator
      task_group_name: group2
      dependencies: []
      outlets: [group2.task1]
    group2.task2:
      operator: airflow.operators.empty.EmptyOperator
      task_group_name: group2
      dependencies: []
      outlets: [group2.task2]

empty_pipeline_teste3:    
  description: This is a dummy pipeline for testing purposes.
  render_template_as_native_obj: True
  schedule: 
    __type__: builtins.list
    items:
      - __type__: airflow.sdk.Asset
        uri: group1.task2
  owner: ['hiroyukii.seo@gmail.com']
  task_groups:
    group3:
      tooltip: This is the first task group.
      dependencies: []
  tasks:
    group3.task1:
      operator: airflow.operators.empty.EmptyOperator
      task_group_name: group3
      dependencies: []
      outlets: [group3.task1]

empty_pipeline_teste4:
  description: This is a dummy pipeline for testing purposes.
  render_template_as_native_obj: True
  schedule: 
    __type__: builtins.list
    items:
      - __type__: airflow.sdk.Asset
        uri: group1.task2
  owner: ['hiroyukii.seo@gmail.com']
  task_groups:
    group4:
      tooltip: This is the first task group.
      dependencies: []
  tasks:
    group4.task1:
      operator: airflow.operators.empty.EmptyOperator
      task_group_name: group4
      dependencies: []
      outlets: [group4.task1]