default_args:
  owner: "default_owner"
  start_date: 2021-01-01
  retries: 1
  retry_delay: 300

example_dag:
  schedule_interval: "0 1 * * *"
  description: Example DAG
  tasks:
    task_1:
      operator: airflow.operators.dummy.DummyOperator
      dependencies: []
    task_2:
      operator: airflow.operators.dummy.DummyOperator
      dependencies:
        - task_1
