default:
  default_args:
    owner: "default_owner"
    start_date: 2018-03-01
    retries: 1
    retry_delay_sec: 300
  concurrency: 1
  max_active_runs: 1
  dagrun_timeout_sec: 600
  default_view: "graph"
  orientation: "LR"
  schedule_interval: "0 1 * * *"

dummy_pipelineaaaaaa:
    description: "This is a dummy pipeline for testing purposes."
    task_groups:
      group1:
        tooltip: "This is the first task group."
      group2:
        tooltip: "This is the second task group."
        
    tasks:
      group1_task1:
        operator: airflow.operators.empty.EmptyOperator
        task_id: "task1"
        task_group_name: "group1"

        group1_task2:
          operator: airflow.operators.empty.EmptyOperator
          task_id: "task2"
          task_group_name: "group1"

        group1_task3:
          operator: airflow.operators.empty.EmptyOperator
          task_id: "task3"
          task_group_name: "group1"
          dependencies: ['task1', 'task2']
