default:
  default_args:
    owner: "default_owner"
    start_date: 2018-03-01
    retries: 1
    retry_delay_sec: 300
  concurrency: 1
  max_active_runs: 1
  dagrun_timeout_sec: 600
  default_view: "graph"
  orientation: "LR"
  schedule_interval: "0 1 * * *"

dummy_pipelineaaaaaa:
  description: "This is a dummy pipeline for testing purposes."
  task_groups:
    tabela:
      tooltip: "this is a task group"
  tasks:
    aaa:
      operator: airflow.operators.empty.EmptyOperator
      task_id: "aaaaa"
    bbb:
      operator: airflow.operators.empty.EmptyOperator
      task_id: "bbbbb"
    ccc:
      operator: airflow.operators.empty.EmptyOperator
      task_id: "ccccc"
      dependencies: [aaa]
