default:
  default_args:
    owner: "default_owner"
    start_date: 2018-03-01
    retries: 1
    retry_delay_sec: 300
  concurrency: 1
  max_active_runs: 1
  dagrun_timeout_sec: 600
  default_view: "graph"
  orientation: "LR"
  schedule_interval: "0 1 * * *"

dummy_pipelineaaaaaa:
    description: "This is a dummy pipeline for testing purposes."
    tasks:
      group1_task1:
        operator: airflow.operators.empty.EmptyOperator
        task_id: "task1"
      group1_task2:
        operator: airflow.operators.empty.EmptyOperator
        task_id: "task2"
      group1_task3:
        operator: airflow.operators.empty.EmptyOperator
        task_id: "task3"
        dependencies: [group1_task1, group1_task2]
